language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10

before_script:
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

script:
  - test -z $(gofmt -s -l ./*.go)
  - go test -v -covermode=count -coverprofile=profile.cov ./...
  - go vet ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN || true
    
